name: Checks

on: push

jobs:
  checks:
    name: Check Branch
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code Base
      uses: actions/checkout@v2

    - name: Read .nvmrc
      run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc | grep -o "[^a-z].*")
      id: nvm

    - name: Setup node v${{ steps.nvm.outputs.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ steps.nvm.outputs.NODE_VERSION }}

    - name: Install modules
      run: npm install 

    - name: Run ESLint
      run: npm run lint

    - name: Run Tests
      run: npm run test
