name: Checks

on: push

jobs:
  checks:
    name: Check Branch
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code Base
      uses: actions/checkout@v2

    - name: Install modules
      run: npm install 

    - name: Run ESLint
      run: npm run lint

    - name: Run Tests
      run: npm run test