name: "Danger JS"

on: pull_request

jobs:
  danger-js:
    name: Danger.js Checks
    runs-on: ubuntu-latest

    steps:    
    - name: Checkout Code Base
      uses: actions/checkout@v2

    - name: Danger JS Action
      uses: danger/danger-js@9.1.8
